### ISSUE TITLE
Number of videos on a row (feed)

### ISSUE THREAD

**Issue by armync** [YouTube-Enhancer/extension#579]
**Is your feature request related to a problem? Please describe.**
YouTube has a layout of 3 videos per row on the subscription feed page.

**Describe the solution you'd like**
This extension should be able to control how many videos to be shown on a row and control the size.

**Comment by VampireChicken12** [comment]
@ArmynC I will look into this. no promises that it will be implemented quick. I have been busy

**Comment by ArmynC** [comment]
Also, an off-topic reference for Stylus extension:

![image](https://github.com/user-attachments/assets/4319e8f6-167a-4313-a11d-62eaac417e9a)

**Comment by VampireChicken12** [comment]
> Also, an off-topic reference for Stylus extension:
> 
> ![image](https://private-user-images.githubusercontent.com/16375271/358016739-4319e8f6-167a-4313-a11d-62eaac417e9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzE2MTUsIm5iZiI6MTcyMzY3MTMxNSwicGF0aCI6Ii8xNjM3NTI3MS8zNTgwMTY3MzktNDMxOWU4ZjYtMTY3YS00MzEzLWExMWQtNjJlYWFjNDE3ZTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIxMzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZTAyZDEwNmUxZmJmZWVkMjczMzZkODVlNTUyMDIxODAyNmIxZDE4MTdjMGJkMDQ5Yjk0MDFmYTcxZDNkZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wqEDq8HLvl38cTKi09gXTL8V0TG_BD-5Y-miOh3cNdc)

thank you. that may just make the feature easy to implement

**Comment by ArmynC** [comment]
There is an complete part, with customizations.

```
@author       Roki_100 & jiraph
@preprocessor stylus
@var          number rows "Number of video rows" 6
@var          checkbox thumbs "Customize thumbnail size" 0
@var          range -width "Thumbnail Size" [1284, 1000, 2000, 'px']
@var          checkbox fullwidth "Force fullscreen width grid" 0
@var          checkbox thumbradius "Customize thumbnail corner radius" 0
@var          range -radius "Thumbnail Corner Radius" [12, 0, 12, 'px']
@var          checkbox channelPage "Activate on channel page" 1
@var          checkbox feedPage "Activate on subscriptions page" 0
@var          checkbox homePage "Activate on home page" 0
@var          checkbox nukeShorts "Nuke Shorts on feed&home (Fixes issues)" 0
@var          checkbox userscript "Enable UserScript Compatibility layer support" 0
@var          number shortsrows "Number of shorts rows (Userscript only)" 8
==/UserStyle== */

exec() {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: rows !important;
        --ytd-rich-grid-posts-per-row: rows !important;
    }

    #contents>ytd-rich-grid-row,
    #contents>ytd-rich-grid-row>#contents {
        display: contents;
    }

    ytd-video-meta-block[rich-meta] #metadata-line.ytd-video-meta-block {
        font-size: 1.2rem;
        line-height: 1.8rem;
        max-height: 3.6rem;
    }

    #video-title.ytd-rich-grid-media {
        font-size: 1.4rem;
        line-height: 2rem;
        max-height: 4rem;
    }

    #header.ytd-rich-grid-renderer {
        width: 100%;
    }

    ytd-rich-item-renderer {
        margin: 8px 2px !important;
        margin-bottom: 24px;
        margin-right: 4px;
        margin-left: 0px;
        width: calc(100%/var(--ytd-rich-grid-items-per-row) - 4px);
    }

    .ytd-two-column-browse-results-renderer {
        padding-inline: 6px;
    }

    if thumbs {
        ytd-two-column-browse-results-renderer.style-scope {
            max-width: -width !important;
        }
        
        ytd-two-column-browse-results-renderer.grid-6-columns {
            width: 100% !important;
        }
    }

    if thumbradius {
        ytd-thumbnail[size="large"] a.ytd-thumbnail, ytd-thumbnail[size="large"]::before {
            border-radius: -radius;
        }
    }

    if fullwidth {
        ytd-two-column-browse-results-renderer.grid:not(.grid-disabled):has(ytd-rich-grid-renderer:not([is-shorts-grid])) {
            max-width: 100% !important;
            width: 100% !important;
        }
    }
}

@-moz-document regexp("^(https?://)(?:www.)?youtube.com/(?:@)?(?:[\w.-]+|(?:c|channel)/[\w-]+)/videos(\?.*)?$") {
    if channelPage {
        exec()
    }
}

@-moz-document regexp("^(https?://)(www\.)?youtube\.com/feed/subscriptions(\?.*)?$") {
    if feedPage {
        exec()
    }

    if nukeShorts {
        [page-subtype="subscriptions"] {
            ytd-item-section-renderer,
            ytd-rich-section-renderer,
            ytd-grid-video-renderer, ytd-rich-item-renderer {
                &:has(a[href^="/shorts/"]) {
                    display: none;
                }
            }
        }
    }

    if userscript {
        :root {
            --rowsfix-by-roki-userscript-rows: rows;
            --rowsfix-by-roki-userscript-shortsrows: shortsrows;
        }
    }
}

@-moz-document regexp("^(https?://)(www\.)?youtube\.com/(/\?.*)?$") {
    if homePage {
        exec()
    }

    if nukeShorts {
        [page-subtype='home'] ytd-rich-section-renderer:has(a[href^="/shorts/"]) {
            display: none;
        }
    }

    if userscript {
        :root {
            --rowsfix-by-roki-userscript-rows: rows;
            --rowsfix-by-roki-userscript-shortsrows: shortsrows;
        }
    }
}
```

alt2: https://github.com/Krishood/UserStyles/blob/main/YouTube/More_Thumbnails_Per_Row.user.css

**Comment by VampireChicken12** [comment]
@ArmynC thank you for your comment I would have to adjust this to work with plain css the extension doesn't use stylus.

**Comment by VampireChicken12** [comment]
@ArmynC I'm going to look into implementing this later today Friday September 27th

**Comment by Seltonu** [comment]
Would also like to request this :) Youtube has slowly been decreasing the number of videos shown on the homepage, I now only see 3 per row (6 total) on my homepage. I would really like to increase to ~5 per row so I can much more quickly scan for content I want to watch

**Comment by VampireChicken12** [comment]
@Seltonu for now until I implement this feature you can use this CSS in the custom CSS editor to accomplish this.

```css
ytd-rich-grid-renderer {
      --ytd-rich-grid-items-per-row: 6 !important;
      --ytd-rich-grid-posts-per-row: 6 !important;
}
ytd-rich-section-renderer:nth-of-type(1),
ytd-rich-section-renderer:nth-of-type(2) {
      display: none;
}
```
Change "6" to the desired amount of videos you want per row, if you set the number too high it can make titles hard to read

**Comment by VampireChicken12** [comment]
@Seltonu thank you for your review on Firefox Add-ons

**Comment by Seltonu** [comment]
@VampireChicken12 wow you're quick haha that worked, thank you! :D

I really appreciate it, is there somewhere I can donate to the project?

**Comment by VampireChicken12** [comment]
> [@VampireChicken12](https://github.com/VampireChicken12) wow you're quick haha that worked, thank you! :D
> 
> I really appreciate it, is there somewhere I can donate to the project?

You're welcome 
https://ko-fi.com/youtubeenhancer

**Comment by VampireChicken12** [comment]
@Seltonu thank you so much for the donation it's greatly appreciated

**Comment by VampireChicken12** [comment]
@Seltonu is there anything you would like to request for the extension?

**Comment by Seltonu** [comment]
@VampireChicken12  I think the only other thing I feel is missing is #248 the Pop-Out mini player when reading comments, I haven't found another extension to do that yet. "Enhancer for Youtube" (different extension) did it but is no longer developed for Firefox and I've been missing it since.

Otherwise I'm thoroughly impressed with how many great features this extension has! I was using 2 other extensions and replaced them with this one, I love it! Great work

**Comment by VampireChicken12** [comment]
> [@VampireChicken12](https://github.com/VampireChicken12) I think the only other thing I feel is missing is [#248](https://github.com/YouTube-Enhancer/extension/issues/248) the Pop-Out mini player when reading comments, I haven't found another extension to do that yet. "Enhancer for Youtube" (different extension) did it but is no longer developed for Firefox and I've been missing it since.
> 
> Otherwise I'm thoroughly impressed with how many great features this extension has! I was using 2 other extensions and replaced them with this one, I love it! Great work

I'll try to work on that, the most I've done was work on a mini preview when hovering over a timestamp #675
Thank you

**Comment by VampireChicken12** [comment]
I have a slight adjustment to the CSS I gave you @Seltonu until 14490c9 is merged and released this fixes the gaps in the videos without hiding latest posts I noticed the previous CSS was doing that sometimes. Also it fixes the left margin on the videos being too much which causes the videos to get too close to the right side of the page like in the attached image
![Image](https://github.com/user-attachments/assets/511e4c9f-00e3-4873-838b-cded1a5130f4)
```css
ytd-rich-grid-renderer {
      --ytd-rich-grid-items-per-row: 6 !important;
      --ytd-rich-grid-posts-per-row: 6 !important;
}

ytd-rich-section-renderer:has([is-shorts]) {
      display: none;
}

ytd-rich-item-renderer[rendered-from-rich-grid][is-in-first-column] {
      margin-left: 8px !important;
}
```

**Comment by Seltonu** [comment]
@VampireChicken12 much appreciate! :) This seems to be working perfectly with no gaps

**Comment by VampireChicken12** [comment]
> [@VampireChicken12](https://github.com/VampireChicken12) much appreciate! :) This seems to be working perfectly with no gaps

you're welcome

**Comment by VampireChicken12** [comment]
I should work on this soon low key 😂

**Comment by Seltonu** [comment]
No rush, the CSS override is still working well! My only trouble with it is it's not aware of window size, so half-screening my browser ends up unusable 😅 

<img width="1249" height="1276" alt="Image" src="https://github.com/user-attachments/assets/2b630ade-e788-47f3-be45-fb661021925b" />

**Comment by VampireChicken12** [comment]
> No rush, the CSS override is still working well! My only trouble with it is it's not aware of window size, so half-screening my browser ends up unusable 😅 
> 
> <img width="1249" height="1276" alt="Image" src="https://github.com/user-attachments/assets/2b630ade-e788-47f3-be45-fb661021925b" />

Oh yea that's unfortunate maybe it could be resolved. I'd still like to add a dedicated feature for this.

**Comment by VampireChicken12** [comment]
give this a try @Seltonu 

```css
ytd-rich-grid-renderer {
    container-type: inline-size;

    --ytd-rich-grid-items-per-row: 6 !important;
    --ytd-rich-grid-posts-per-row: 6 !important;
}

@container (max-width: 1900px) {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: 5 !important;
        --ytd-rich-grid-posts-per-row: 5 !important;
    }
}

@container (max-width: 1550px) {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: 4 !important;
        --ytd-rich-grid-posts-per-row: 4 !important;
    }
}

@container (max-width: 1200px) {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: 3 !important;
        --ytd-rich-grid-posts-per-row: 3 !important;
    }
}

@container (max-width: 800px) {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: 2 !important;
        --ytd-rich-grid-posts-per-row: 2 !important;
    }
}

@container (max-width: 500px) {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: 1 !important;
        --ytd-rich-grid-posts-per-row: 1 !important;
    }
}
```

**Comment by VampireChicken12** [comment]
> give this a try [@Seltonu](https://github.com/Seltonu)
> 
> ytd-rich-grid-renderer {
>     container-type: inline-size;
> 
>     --ytd-rich-grid-items-per-row: 6 !important;
>     --ytd-rich-grid-posts-per-row: 6 !important;
> }
> 
> @container (max-width: 1900px) {
>     ytd-rich-grid-renderer {
>         --ytd-rich-grid-items-per-row: 5 !important;
>         --ytd-rich-grid-posts-per-row: 5 !important;
>     }
> }
> 
> @container (max-width: 1550px) {
>     ytd-rich-grid-renderer {
>         --ytd-rich-grid-items-per-row: 4 !important;
>         --ytd-rich-grid-posts-per-row: 4 !important;
>     }
> }
> 
> @container (max-width: 1200px) {
>     ytd-rich-grid-renderer {
>         --ytd-rich-grid-items-per-row: 3 !important;
>         --ytd-rich-grid-posts-per-row: 3 !important;
>     }
> }
> 
> @container (max-width: 800px) {
>     ytd-rich-grid-renderer {
>         --ytd-rich-grid-items-per-row: 2 !important;
>         --ytd-rich-grid-posts-per-row: 2 !important;
>     }
> }
> 
> @container (max-width: 500px) {
>     ytd-rich-grid-renderer {
>         --ytd-rich-grid-items-per-row: 1 !important;
>         --ytd-rich-grid-posts-per-row: 1 !important;
>     }
> }

I tested this and realized it didn't do anything lmfao

this should work 

```css
ytd-rich-grid-renderer {
    --ytd-rich-grid-items-per-row: 6 !important;
    --ytd-rich-grid-posts-per-row: 6 !important;
}

@media (max-width: 1800px) {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: 5 !important;
        --ytd-rich-grid-posts-per-row: 5 !important;
    }
}

@media (max-width: 1500px) {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: 4 !important;
        --ytd-rich-grid-posts-per-row: 4 !important;
    }
}

@media (max-width: 1200px) {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: 3 !important;
        --ytd-rich-grid-posts-per-row: 3 !important;
    }
}

@media (max-width: 800px) {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: 2 !important;
        --ytd-rich-grid-posts-per-row: 2 !important;
    }
}

@media (max-width: 500px) {
    ytd-rich-grid-renderer {
        --ytd-rich-grid-items-per-row: 1 !important;
        --ytd-rich-grid-posts-per-row: 1 !important;
    }
}

ytd-rich-item-renderer[rendered-from-rich-grid][is-in-first-column] {
    margin-left: 8px !important;
}
```
